<?php
/**
 * AdditionalProductIdentityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API to View & Search for Items
 *
 * The Browse API lets shoppers search for specific items by keyword, category, product, or item aspects and retrieve the details of an item.
 *
 * OpenAPI spec version: v1_beta.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AdditionalProductIdentityTest Class Doc Comment
 *
 * @category    Class */
// * @description The type that defines the array of additional product type/value pairs for the same product associated with an item. A product can have more than one identifier value for a product type, such as UPC or EAN. For example, the same product UPC can have an identifier that is 12, 13, or 14 digits. This container returns all the identifiers for each product Id type. These are in addition to the identifiers returned in the &lt;b&gt; mpn&lt;/b&gt; and &lt;b&gt; gitn&lt;/b&gt; fields.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdditionalProductIdentityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AdditionalProductIdentity"
     */
    public function testAdditionalProductIdentity()
    {
    }

    /**
     * Test attribute "product_identity"
     */
    public function testPropertyProductIdentity()
    {
    }
}
