<?php
/**
 * EstimatedAvailabilityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API to View & Search for Items
 *
 * The Browse API lets shoppers search for specific items by keyword, category, product, or item aspects and retrieve the details of an item.
 *
 * OpenAPI spec version: v1_beta.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EstimatedAvailabilityTest Class Doc Comment
 *
 * @category    Class */
// * @description The type that defines the fields for the estimated item availability information.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EstimatedAvailabilityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EstimatedAvailability"
     */
    public function testEstimatedAvailability()
    {
    }

    /**
     * Test attribute "availability_threshold"
     */
    public function testPropertyAvailabilityThreshold()
    {
    }

    /**
     * Test attribute "availability_threshold_type"
     */
    public function testPropertyAvailabilityThresholdType()
    {
    }

    /**
     * Test attribute "delivery_options"
     */
    public function testPropertyDeliveryOptions()
    {
    }

    /**
     * Test attribute "estimated_availability_status"
     */
    public function testPropertyEstimatedAvailabilityStatus()
    {
    }

    /**
     * Test attribute "estimated_available_quantity"
     */
    public function testPropertyEstimatedAvailableQuantity()
    {
    }

    /**
     * Test attribute "estimated_sold_quantity"
     */
    public function testPropertyEstimatedSoldQuantity()
    {
    }
}
