<?php
/**
 * ProductIdentityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API to View & Search for Items
 *
 * The Browse API lets shoppers search for specific items by keyword, category, product, or item aspects and retrieve the details of an item.
 *
 * OpenAPI spec version: v1_beta.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductIdentityTest Class Doc Comment
 *
 * @category    Class */
// * @description The type that defines the fields for the type/value pairs of product associated with an item. &lt;br /&gt;&lt;br /&gt;For example: &lt;br /&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;code&gt;\&quot;identifierType\&quot;: \&quot;BRAND\&quot;&lt;/code&gt; and  &lt;code&gt;\&quot;identifierValue\&quot;: \&quot;Apple\&quot;&lt;/code&gt;&lt;br /&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;code&gt;\&quot;identifierType\&quot;: \&quot;MPN\&quot;&lt;/code&gt;, and &lt;code&gt;\&quot;identifierValue\&quot;: \&quot;MC978LLA\&quot;&lt;br /&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;code&gt;\&quot;identifierType\&quot;: \&quot;UPC\&quot; and \&quot;identifierValue\&quot;: \&quot;0885909470105\&quot;&lt;/code&gt;.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductIdentityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductIdentity"
     */
    public function testProductIdentity()
    {
    }

    /**
     * Test attribute "identifier_type"
     */
    public function testPropertyIdentifierType()
    {
    }

    /**
     * Test attribute "identifier_value"
     */
    public function testPropertyIdentifierValue()
    {
    }
}
