<?php
/**
 * RefinementTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API to View & Search for Items
 *
 * The Browse API lets shoppers search for specific items by keyword, category, product, or item aspects and retrieve the details of an item.
 *
 * OpenAPI spec version: v1_beta.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RefinementTest Class Doc Comment
 *
 * @category    Class */
// * @description This type defines the fields for the various refinements of an item. You can use the information in this contain to create histograms, which help shopper choose exactly what they want.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RefinementTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Refinement"
     */
    public function testRefinement()
    {
    }

    /**
     * Test attribute "aspect_distributions"
     */
    public function testPropertyAspectDistributions()
    {
    }

    /**
     * Test attribute "buying_option_distributions"
     */
    public function testPropertyBuyingOptionDistributions()
    {
    }

    /**
     * Test attribute "category_distributions"
     */
    public function testPropertyCategoryDistributions()
    {
    }

    /**
     * Test attribute "condition_distributions"
     */
    public function testPropertyConditionDistributions()
    {
    }

    /**
     * Test attribute "dominant_category_id"
     */
    public function testPropertyDominantCategoryId()
    {
    }
}
