<?php
/**
 * SellerLegalInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API to View & Search for Items
 *
 * The Browse API lets shoppers search for specific items by keyword, category, product, or item aspects and retrieve the details of an item.
 *
 * OpenAPI spec version: v1_beta.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SellerLegalInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description The type that defines the fields for the contact information for a seller.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SellerLegalInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SellerLegalInfo"
     */
    public function testSellerLegalInfo()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "imprint"
     */
    public function testPropertyImprint()
    {
    }

    /**
     * Test attribute "legal_contact_first_name"
     */
    public function testPropertyLegalContactFirstName()
    {
    }

    /**
     * Test attribute "legal_contact_last_name"
     */
    public function testPropertyLegalContactLastName()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "registration_number"
     */
    public function testPropertyRegistrationNumber()
    {
    }

    /**
     * Test attribute "seller_provided_legal_address"
     */
    public function testPropertySellerProvidedLegalAddress()
    {
    }

    /**
     * Test attribute "terms_of_service"
     */
    public function testPropertyTermsOfService()
    {
    }

    /**
     * Test attribute "vat_details"
     */
    public function testPropertyVatDetails()
    {
    }
}
