<?php
/**
 * ShippingOptionSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API to View & Search for Items
 *
 * The Browse API lets shoppers search for specific items by keyword, category, product, or item aspects and retrieve the details of an item.
 *
 * OpenAPI spec version: v1_beta.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ShippingOptionSummaryTest Class Doc Comment
 *
 * @category    Class */
// * @description The type that defines the fields for the shipping information.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShippingOptionSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingOptionSummary"
     */
    public function testShippingOptionSummary()
    {
    }

    /**
     * Test attribute "max_estimated_delivery_date"
     */
    public function testPropertyMaxEstimatedDeliveryDate()
    {
    }

    /**
     * Test attribute "min_estimated_delivery_date"
     */
    public function testPropertyMinEstimatedDeliveryDate()
    {
    }

    /**
     * Test attribute "shipping_cost"
     */
    public function testPropertyShippingCost()
    {
    }

    /**
     * Test attribute "shipping_cost_type"
     */
    public function testPropertyShippingCostType()
    {
    }
}
