<?php
/**
 * TaxesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API to View & Search for Items
 *
 * The Browse API lets shoppers search for specific items by keyword, category, product, or item aspects and retrieve the details of an item.
 *
 * OpenAPI spec version: v1_beta.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TaxesTest Class Doc Comment
 *
 * @category    Class */
// * @description The type that defines the tax fields.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaxesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Taxes"
     */
    public function testTaxes()
    {
    }

    /**
     * Test attribute "included_in_price"
     */
    public function testPropertyIncludedInPrice()
    {
    }

    /**
     * Test attribute "shipping_and_handling_taxed"
     */
    public function testPropertyShippingAndHandlingTaxed()
    {
    }

    /**
     * Test attribute "tax_jurisdiction"
     */
    public function testPropertyTaxJurisdiction()
    {
    }

    /**
     * Test attribute "tax_percentage"
     */
    public function testPropertyTaxPercentage()
    {
    }

    /**
     * Test attribute "tax_type"
     */
    public function testPropertyTaxType()
    {
    }
}
